name: azure_jenkins_exp
# label used for menu selection
label: Step 1 - Azure Jenkins Infrastructure Deployment Build

description: >
  This skillet deploys the Security Framework Azure Jenkins environment.  The template deploys the Following:
  Azure VNETS's, Route Tables, Subnets, Availability Zones, Load Balancers and Native Security tools WAF and Network Security Groups.
  The Template will also deploy Palo Alto Networks Firewall with security posture.
# type of skillet (panos or panorama or template or terraform)
type: python3

# more complex skillets may express a dependency on another skillet that should be loaded before this one.
# For example, a set of skillets may build off of a single 'golden config' that contains shared configuration
# As this skillet is very simple, there is no need to build on another one.
extends:

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  collection: McGillicSkillet

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:
  - name: username
    description: FW Username
    default: panadmin
    type_hint: text
  - name: password
    description: FW Password
    default:
    type_hint: password
  - name: resource_group
    description: Azure Resource Group
    default: cloud-security-framework-changeme
    type_hint: text
  - name: azure_region
    description: Azure Region
    default: centralus
    type_hint: dropdown
    dd_list:
     - key: "West US"
       value: "westus"
     - key: "West US 2"
       value: "westus2"
     - key: "West Central US"
       value: "westcentralus"
     - key: "East US"
       value: "eastus"
     - key: "East US 2"
       value: "eastus2"
     - key: "Central US"
       value: "centralus"
     - key: "North Central US"
       value: "northcentralus"
     - key: "South Central US"
       value: "southcentralus"
     - key: "Canada Central"
       value: "canadacentral"
     - key: "Canada East"
       value: "canadaeast"
     - key: "UK West"
       value: "ukwest"
     - key: "UK South"
       value: "uksouth"
     - key: "North Europe"
       value: "northeurope"
     - key: "West Europe"
       value: "westeurope"
     - key: "Australia East"
       value: "australiaeast"
     - key: "Australia Southeast"
       value: "australiasoutheast"
     - key: "Australia Central"
       value: "australiacentral"
     - key: "Australia Central 2"
       value: "australiacentral2"
     - key: "East Asia"
       value: "eastasia"
     - key: "South East Asia"
       value: "southeastasia"
     - key: "Korea Central"
       value: "koreacentral"
     - key: "Korea South"
       value: "koreasouth"
     - key: "Japan West"
       value: "japanwest"
     - key: "Japan East"
       value: "japaneast"
     - key: "South India"
       value: "southindia"
     - key: "Central India"
       value: "centralindia"
     - key: "West India"
       value: "westindia"
     - key: "Brazil South"
       value: "brazilsouth"
     - key: "France Central"
       value: "francecentral"
     - key: "France South"
       value: "francesouth"
 # - name: azure_region
 #   description: Azure Region
 #   default: centralus
 #   type_hint: text
    
    
# Snippets is an ordered list of configuration xml fragments that will be pushed to the PAN-OS NGFW. The xpath
# determines where in the configuration hierarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: script
    file: ../../deploy.py
